info:
  contact: {}
paths:
  /api/addarticle:
    post:
      consumes:
      - multipart/form-data
      description: title category只能为0 或1 content token 为必填
      parameters:
      - description: 文章标题
        in: formData
        name: title
        required: true
        type: string
      - description: 文章分类 0为技术类 1为生活类
        in: formData
        name: category
        required: true
        type: string
      - description: '文章内容 '
        in: formData
        name: content
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"添加成功！"}'
          schema:
            type: string
      summary: 添加文章接口
      tags:
      - 私有方法
  /api/deletearticle:
    delete:
      consumes:
      - application/json
      description: identification token为必填
      parameters:
      - description: 文章唯一标识
        in: query
        name: identification
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{ "code": 1, "err": "删除文章不存在或者已经删除！" }'
          schema:
            type: string
      summary: 删除文章接口
      tags:
      - 私有方法
  /api/examinecomment:
    get:
      consumes:
      - application/json
      description: comment_id status content token  为必填
      parameters:
      - description: 评论唯一标识
        in: query
        name: comment_id
        required: true
        type: string
      - description: 审核状态 0 表示未审核 1 表示审核通过 2 表示审核不通过
        in: query
        name: status
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{ "code": 200, "msg": "审核成功！" }'
          schema:
            type: string
      summary: 审核评论接口
      tags:
      - 私有方法
  /api/login:
    post:
      consumes:
      - multipart/form-data
      description: 用户名 密码 为必填
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "msg": "登陆成功","token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmRlbnRseSI6IjZhMmE0NjJjLWExMDctNDhlYS04MmU1LTc0ZTMwODMyN2U2ZiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpc3MiOiJ0ZXN0IiwiZXhwIjoxNjc4Nzg2NTM1fQ.P4dJ_f2UGhKbpiIqHxTxghRKwKIlCpF2XjryHCSnKKk"}'
          schema:
            type: ""
      summary: 登录接口
      tags:
      - 私有方法
  /api/updatearticle:
    get:
      consumes:
      - application/json
      description: identification content category title 为必填
      parameters:
      - description: 文章唯一标识
        in: query
        name: identification
        required: true
        type: string
      - description: 文章内容
        in: query
        name: content
        required: true
        type: string
      - description: 文章分类
        in: query
        name: category
        required: true
        type: string
      - description: 文章标题
        in: query
        name: title
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{ "code": 200, "msg": "更新成功！" }'
          schema:
            type: string
      summary: 更新文章接口
      tags:
      - 私有方法
  /user/addcomments:
    post:
      consumes:
      - multipart/form-data
      description: article_id content token  为必填
      parameters:
      - description: 文章唯一标识
        in: formData
        name: article_id
        required: true
        type: string
      - description: 父级评论
        in: formData
        name: parent_id
        type: string
      - description: 评论内容
        in: formData
        name: content
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"评论成功！"}'
          schema:
            type: string
      summary: 发布评论接口
      tags:
      - 公共方法
  /user/articlelist:
    get:
      consumes:
      - application/json
      description: token 为必填
      parameters:
      - description: 页数,不填默认为1
        in: query
        name: page
        type: string
      - description: 每页大小，默认为20
        in: query
        name: number
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: "{\"code\": 200,\t\"data\": {\"length\": 4, \"list\": [\t{\t\"id\":
            1, \"identification\": \"1068dcc0-4fd3-461d-9f4b-0100879457eb\",\t\"content\":
            \"1\",\t\"status\": 0,\t\"title\": \"1\",\t\"create_time\": \"1686055918562468\",\t\"ip\":
            \"127.0.0.1\", \"update_time\": \"1\", \"category\": \"1\" },]},\"msg\":
            \"获取数据成功！\"}"
          schema:
            type: string
      summary: 获取文章接口
      tags:
      - 公共方法
  /user/commentlist:
    get:
      consumes:
      - application/json
      description: article_id  token  为必填
      parameters:
      - description: 文章唯一标识
        in: query
        name: article_id
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: "{\"code\": 200,\"data\": {\"list\": [{\"id\": 1,\"article_id\":
            \"52fd3b87-9572-4330-9371-9b7cf54628a2\",\t\"user_id\": \"e5a6071b-baaf-45aa-a587-784d0ff9a575\",\t\"parent_id\":
            \"\",\"comment_id\": \"\",\"content\": \"哈哈哈\",\"status\": 0,\"created_time\":
            \"2023-06-09T17:26:30Z\", \"updated_time\": \"2023-06-09T17:26:30Z\"\t},{\"id\":
            2,\"article_id\": \"52fd3b87-9572-4330-9371-9b7cf54628a2\", \"user_id\":
            \"e5a6071b-baaf-45aa-a587-784d0ff9a575\",\"parent_id\": \"\",\"comment_id\":
            \"e725fe87-a881-4cc9-ad7a-bc48ccdb97dd\",\"content\": \"哈哈哈\", \"status\":
            0,\"created_time\": \"2023-06-09T17:46:38Z\", \"updated_time\": \"2023-06-09T17:46:38Z\"\t},
            ] }, \"msg\": \"获取数据成功！\"} "
          schema:
            type: string
      summary: 获取评论接口
      tags:
      - 公共方法
  /user/file:
    post:
      consumes:
      - application/json
      description: |-
        上传文件
        file token为必填
      parameters:
      - description: 表单name
        in: formData
        name: file
        required: true
        type: file
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":1,"msg":"\u0001个文件上传成功","url":"127.0.0.1:8080/img/12.png"}'
          schema:
            type: string
      summary: 上传文件接口
      tags:
      - 公共方法
  /user/login:
    post:
      consumes:
      - multipart/form-data
      description: 用户名 密码 为必填
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "msg": "登陆成功","token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmRlbnRseSI6IjZhMmE0NjJjLWExMDctNDhlYS04MmU1LTc0ZTMwODMyN2U2ZiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpc3MiOiJ0ZXN0IiwiZXhwIjoxNjc4Nzg2NTM1fQ.P4dJ_f2UGhKbpiIqHxTxghRKwKIlCpF2XjryHCSnKKk"}'
          schema:
            type: ""
      summary: 登录接口
      tags:
      - 公共方法
  /user/logout:
    get:
      consumes:
      - application/json
      description: token 为必填
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{ "code": 200, "msg": "退出登录成功！" }'
          schema:
            type: ""
      summary: 退出登录接口
      tags:
      - 公共方法
  /user/picture:
    get:
      consumes:
      - application/json
      description: |-
        生成图片
        file token为必填
      parameters:
      - description: 要显示的文字
        in: query
        name: str
        required: true
        type: string
      - description: token
        in: header
        name: token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 图片文件
          schema:
            type: string
      summary: 生成图片接口
      tags:
      - 公共方法
  /user/register:
    post:
      consumes:
      - multipart/form-data
      description: 用户名 密码 邮箱 为必填
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: "{\t\"code\": 200,\t\"msg\": \"注册成功！\" \t}"
          schema:
            type: ""
      summary: 注册接口
      tags:
      - 公共方法
swagger: "2.0"
