info:
  contact: {}
paths:
  /user/addarticle:
    post:
      consumes:
      - multipart/form-data
      description: title category只能为0 或1 content token 为必填
      parameters:
      - description: 文章标题
        in: formData
        name: title
        required: true
        type: string
      - description: 文章分类 0为技术类 1为生活类
        in: formData
        name: category
        required: true
        type: string
      - description: '文章内容 '
        in: formData
        name: content
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"添加成功！"}'
          schema:
            type: string
      summary: 添加文章接口
      tags:
      - 公共方法
  /user/articlelist:
    get:
      consumes:
      - application/json
      description: token 为必填
      parameters:
      - description: 页数,不填默认为1
        in: query
        name: page
        type: string
      - description: 每页大小，默认为20
        in: query
        name: number
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: "{\"code\": 200,\t\"data\": {\"length\": 4, \"list\": [\t{\t\"id\":
            1, \"identification\": \"1068dcc0-4fd3-461d-9f4b-0100879457eb\",\t\"content\":
            \"1\",\t\"status\": 0,\t\"title\": \"1\",\t\"create_time\": \"1686055918562468\",\t\"ip\":
            \"127.0.0.1\", \"update_time\": \"1\", \"category\": \"1\" },]},\"msg\":
            \"获取数据成功！\"}"
          schema:
            type: string
      summary: 获取文章接口
      tags:
      - 公共方法
  /user/deletearticle:
    delete:
      consumes:
      - application/json
      description: identification token为必填
      parameters:
      - description: 文章唯一标识
        in: query
        name: identification
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{ "code": 1, "err": "删除文章不存在或者已经删除！" }'
          schema:
            type: string
      summary: 删除文章接口
      tags:
      - 公共方法
  /user/login:
    post:
      consumes:
      - multipart/form-data
      description: 用户名 密码 为必填
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 200, "msg": "登陆成功","token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpbmRlbnRseSI6IjZhMmE0NjJjLWExMDctNDhlYS04MmU1LTc0ZTMwODMyN2U2ZiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpc3MiOiJ0ZXN0IiwiZXhwIjoxNjc4Nzg2NTM1fQ.P4dJ_f2UGhKbpiIqHxTxghRKwKIlCpF2XjryHCSnKKk"}'
          schema:
            type: ""
      summary: 登录接口
      tags:
      - 公共方法
  /user/logout:
    get:
      consumes:
      - application/json
      description: token 为必填
      parameters:
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{ "code": 200, "msg": "退出登录成功！" }'
          schema:
            type: ""
      summary: 退出登录接口
      tags:
      - 公共方法
  /user/register:
    post:
      consumes:
      - multipart/form-data
      description: 用户名 密码 邮箱 为必填
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 邮箱
        in: formData
        name: email
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{'
          schema:
            type: ""
      summary: 注册接口
      tags:
      - 公共方法
  /user/updatearticle:
    get:
      consumes:
      - application/json
      description: identification content category title 为必填
      parameters:
      - description: 文章唯一标识
        in: query
        name: identification
        required: true
        type: string
      - description: 文章内容
        in: query
        name: content
        required: true
        type: string
      - description: 文章分类
        in: query
        name: category
        required: true
        type: string
      - description: 文章标题
        in: query
        name: title
        required: true
        type: string
      - description: token
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code":200,"msg":"添加成功！"}'
          schema:
            type: string
      summary: 更新文章接口
      tags:
      - 公共方法
swagger: "2.0"
